name: Format

on:
  push:
    branches:
      - main

jobs:
  swift_format:
    name: swift-format
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - name: Install swift-format
        run: |
          brew install swift-format

      - name: Format
        run: swift-format format --recursive --in-place Sources Tests

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Run swift-format
          branch: 'main'
